require 'rake/clean'

ID3LIB = 'id3lib-3.8.3'

PREFIX = File.expand_path("./prefix")

CLEAN.include "*.o", "src", "prefix"
CLOBBER.include "tars"


task :default => ["prefix/lib/libid3.a"]

file "prefix/lib/libid3.a" => ["src/#{ID3LIB}/config.log"] do
  sh <<-CMD
    cd src/#{ID3LIB}
    CFLAGS="-Os" CXXFLAGS="-Os -DID3LIB_LINKOPTION=1" \
      ./configure --host=i586-mingw32msvc --prefix=#{PREFIX}
    make && make install
  CMD
end

file "src/#{ID3LIB}/config.log" => ["tars/#{ID3LIB}.tar.gz"] do
  sh "mkdir src; cd src; tar xzf ../tars/#{ID3LIB}.tar.gz"
  FileList["patches/#{ID3LIB}-*"].each do |f|
    sh "patch -d src -N -p0 < #{f}"
  end
end

file "tars/#{ID3LIB}.tar.gz" do
  sh "mkdir tars; cd tars; wget http://dl.sourceforge.net/sourceforge/id3lib/#{ID3LIB}.tar.gz"
end
